### ISSUE TITLE
Invalid Version Files

### ISSUE THREAD

**Issue by srandalls** [tsee/Perl-APIReference#1]
1) Perl/APIReference/V5_015_001.pm: Missing?
2) Perl/APIReference/V5_015_005.pm: Missing?
3) Perl/APIReference/V5_016_001.pm: Self-inheriting.
3) Perl/APIReference/V5_016_002.pm: Self-inheriting.

**Comment by tsee** [comment]
This isn't an issue any more, I believe. (Sorry for the ridiculously slow turnaround time.)
